name       : libfs
version    : 1.0.8
release    : 12
source     :
    - http://xorg.freedesktop.org/releases/individual/lib/libFS-1.0.8.tar.gz : e3da723257f4f4c0c629aec402e0a36fbec66a9418f70d24a159cb0470ec83d2
license    : MIT
summary    : X Font Service client library
component  : xorg.library
description: |
    This library is used by clients of X Font Servers (xfs), such as xfsinfo, xfslsfonts, and the X servers themselves.
emul32     : yes
builddeps  :
    - pkgconfig32(x11)
    - pkgconfig(xproto)
    - pkgconfig(xtrans)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
