name        : libfs
version     : 1.0.7
release     : 6
source     :
    - http://xorg.freedesktop.org/releases/individual/lib/libFS-1.0.7.tar.gz : 91bf1c5ce4115b7dbf4e314fdbee54052708e8f7b6a2ec6e82c309bcbe40ef3d
license     :
    - MIT
summary     : X Font Service client library
component   : xorg.library
builddeps   :
    - pkgconfig(fontsproto)
    - pkgconfig(xtrans)
    - pkgconfig(x11)
    - pkgconfig32(x11)
    - glibc-32bit-devel
    - libgcc-32bit
emul32      : yes
description : |
    This library is used by clients of X Font Servers (xfs), such as xfsinfo, xfslsfonts, and the X servers themselves.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
