name       : libfs
version    : 1.0.9
release    : 13
source     :
    - http://xorg.freedesktop.org/releases/individual/lib/libFS-1.0.9.tar.gz : 8bc2762f63178905228a28670539badcfa2c8793f7b6ce3f597b7741b932054a
license    : MIT
summary    : X Font Service client library
component  : xorg.library
description: |
    This library is used by clients of X Font Servers (xfs), such as xfsinfo, xfslsfonts, and the X servers themselves.
emul32     : yes
builddeps  :
    - pkgconfig32(x11)
    - pkgconfig(xproto)
    - pkgconfig(xtrans)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
